# [build]
# target = [
#     "x86_64-pc-windows-msvc",
#     "x86_64-apple-darwin",
#     "x86_64-apple-ios",
#     "x86_64-unknown-linux-gnu",
#     "aarch64-apple-darwin",
#     "aarch64-apple-ios",
#     "aarch64-unknown-linux-gnu",
#     "i686-linux-android",
#     "i686-pc-windows-msvc",
#     "i686-unknown-linux-gnu"
# ]
